package constitution_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/convergent-systems-co/aiConstitution/src/internal/constitution"
)

func TestLoadUnified_ReadsConstitutionMD(t *testing.T) {
	root := t.TempDir()
	_ = os.WriteFile(filepath.Join(root, "Constitution.md"),
		[]byte("# Unified\n\n## §1 Governance\nGov content here."), 0o600)

	unified, err := constitution.LoadUnified(root)
	if err != nil {
		t.Fatalf("LoadUnified() error: %v", err)
	}
	if !strings.Contains(unified.Content, "§1 Governance") {
		t.Error("unified content missing expected section")
	}
	if unified.Local != "" {
		t.Error("Local should be empty when Constitution.local.md absent")
	}
}

func TestLoadUnified_MissingFile_ReturnsError(t *testing.T) {
	root := t.TempDir()
	_, err := constitution.LoadUnified(root)
	if err == nil {
		t.Error("expected error when Constitution.md missing")
	}
}

func TestLoadUnified_IncludesLocalOverride(t *testing.T) {
	root := t.TempDir()
	_ = os.WriteFile(filepath.Join(root, "Constitution.md"), []byte("# Main"), 0o600)
	_ = os.WriteFile(filepath.Join(root, "Constitution.local.md"), []byte("# Local override"), 0o600)

	unified, err := constitution.LoadUnified(root)
	if err != nil {
		t.Fatalf("LoadUnified() error: %v", err)
	}
	if unified.Local == "" {
		t.Error("Local should be populated when Constitution.local.md present")
	}
}

func TestFileStatusV2_DetectsUnifiedLayout(t *testing.T) {
	root := t.TempDir()
	_ = os.WriteFile(filepath.Join(root, "Constitution.md"), []byte("# Unified"), 0o600)

	status := constitution.FileStatusV2(root)
	if !status["Constitution.md"] {
		t.Error("Constitution.md should be present")
	}
	if !status["v2"] {
		t.Error("v2 should be true when only Constitution.md present (no Common.md)")
	}
}

func TestFileStatusV2_DetectsLegacyLayout(t *testing.T) {
	root := t.TempDir()
	for _, f := range []string{"Constitution.md", "Common.md", "Code.md", "Writing.md"} {
		_ = os.WriteFile(filepath.Join(root, f), []byte("# "+f), 0o600)
	}
	status := constitution.FileStatusV2(root)
	if status["v2"] {
		t.Error("v2 should be false when Common.md is present (legacy layout)")
	}
}

func TestParseSectionsExtractsPersonaRules(t *testing.T) {
	content := `# AI Constitution

## 0. Governance Rules
Some meta text.

## 1. Common Rules
**P1. Honesty.** MUST NOT fabricate.

**P2. Cost ceiling.** Ask before exceeding $5.

## 2. Code Rules
**2.1 Function length.** Functions MUST be ≤30 lines.
`
	sections := constitution.ParseSections(content)
	if len(sections) != 2 {
		t.Fatalf("ParseSections: got %d sections, want 2 (Governance skipped)", len(sections))
	}
	if sections[0].Number != 1 || sections[0].Name != "Common" || sections[0].Slug != "common" || sections[0].FileName != "Common.md" {
		t.Errorf("sections[0] = %+v, want Number=1 Name=Common Slug=common FileName=Common.md", sections[0])
	}
	if sections[1].Number != 2 || sections[1].Name != "Code" || sections[1].Slug != "code" || sections[1].FileName != "Code.md" {
		t.Errorf("sections[1] = %+v", sections[1])
	}
}

func TestParseSectionsBodyContent(t *testing.T) {
	content := `## 1. Common Rules
**P1. Honesty.** MUST NOT fabricate.
## 2. Code Rules
**2.1 Length.** MUST be ≤30 lines.
`
	sections := constitution.ParseSections(content)
	if !strings.Contains(sections[0].Body, "Honesty") {
		t.Errorf("sections[0].Body missing expected content, got: %q", sections[0].Body)
	}
	if !strings.Contains(sections[1].Body, "Length") {
		t.Errorf("sections[1].Body missing expected content, got: %q", sections[1].Body)
	}
}

func TestParseSectionsEmptyReturnsNil(t *testing.T) {
	if got := constitution.ParseSections(""); len(got) != 0 {
		t.Errorf("ParseSections(\"\") = %v, want empty", got)
	}
}

// TestParseSectionsAny_LegacyFormat verifies backward compatibility with
// the "## N. Name Rules" format.
func TestParseSectionsAny_LegacyFormat(t *testing.T) {
	content := "## 1. Common Rules\nSome rules.\n\n## 2. Code Rules\nMore rules.\n"
	secs := constitution.ParseSectionsAny(content)
	if len(secs) != 2 {
		t.Fatalf("expected 2 sections for legacy format, got %d", len(secs))
	}
	if secs[0].Name != "Common" || secs[0].Number != 1 {
		t.Errorf("unexpected first section: %+v", secs[0])
	}
}

// TestParseSectionsAny_TemplateFormat verifies the "## §N Name" format
// generated by the constitution template.
func TestParseSectionsAny_TemplateFormat(t *testing.T) {
	content := "## §3 Universal Rules\n**U1. State assumptions.** MUST name gaps.\n\n## §4 Technical Work\n**P1. Clean code.** MUST be readable.\n"
	secs := constitution.ParseSectionsAny(content)
	if len(secs) != 2 {
		t.Fatalf("expected 2 sections for template format, got %d: %+v", len(secs), secs)
	}
	if secs[0].Number != 3 {
		t.Errorf("expected section 3, got %d", secs[0].Number)
	}
	if secs[1].Number != 4 {
		t.Errorf("expected section 4, got %d", secs[1].Number)
	}
}

// TestParseSectionsAny_GovernanceExcluded verifies that §1 Governance is
// excluded (contains meta-rules, not enforceable AI directives).
func TestParseSectionsAny_GovernanceExcluded(t *testing.T) {
	content := "## §1 Governance\nSome meta-rules.\n\n## §3 Universal Rules\n**U1. MUST.** Do this.\n"
	secs := constitution.ParseSectionsAny(content)
	for _, s := range secs {
		if strings.EqualFold(s.Name, "Governance") || s.Number == 1 {
			t.Errorf("Governance section should be excluded: %+v", s)
		}
	}
	if len(secs) != 1 {
		t.Errorf("expected 1 section (§3 only), got %d: %+v", len(secs), secs)
	}
}
