package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"text/template"
)

// auditReviewPrompt is read-only: no shell execution allowed in the scheduled
// review. The review writes proposals to ~/.ai/governance/plans/ for human
// approval. The human then runs: ai amend apply && ai setup --no-hooks
const auditReviewPrompt = `Review the AI governance audit logs and write a constitutional amendment proposal.

You have read-only + write-to-plans access. Do NOT run shell commands.

Steps:
1. Read all files in ~/.ai/audit/violations/ — these record rule violations
2. Read all files in ~/.ai/audit/overrides/ — these record intentional relaxations
3. Analyze patterns: which rules fire most, which overrides recur, any gaps or contradictions
4. Write a proposal file to ~/.ai/governance/plans/audit-review-YYYYMMDD.md
   (replace YYYYMMDD with today's date) containing:
   - Violations reviewed: count + date range
   - Overrides reviewed: count
   - Patterns found: bulleted list with evidence
   - Proposed amendments: for each, quote the current rule text, propose the
     revised text, and explain the rationale in one sentence
5. Do NOT modify Constitution.md or any existing file outside governance/plans/

The human will review the proposal and run: ai amend apply && ai setup --no-hooks
`

// memoryReviewPrompt is read-only: no shell execution allowed in the scheduled
// review. Trivial fixes (typos, broken index links) may be applied directly;
// structural changes go to a proposal file for human approval.
const memoryReviewPrompt = `Review all persistent AI memories and write an update proposal.

You have read + write access to ~/.ai/memory/ and ~/.ai/governance/plans/ only.
Do NOT run shell commands.

Steps:
1. Read ~/.ai/memory/MEMORY.md (the index file)
2. Read each memory file linked from the index
3. For each memory assess: staleness, accuracy, redundancy, relevance
4. Look for gaps: important facts about the user or project not yet captured
5. Apply trivial fixes directly (typos, broken links in MEMORY.md index only)
6. Write a proposal file to ~/.ai/governance/plans/memory-review-YYYYMMDD.md
   (replace YYYYMMDD with today's date) containing:
   - Memories reviewed: count
   - Trivial fixes applied: list (or "none")
   - Proposed updates grouped by: Update / Delete / Add
     For Add: include full draft content with frontmatter
   - Healthy memories: brief list of ones that are current and accurate

The human will review the proposal, apply changes, then run: ai setup --no-hooks
`

// posixReviewScript runs claude with an explicit tool allowlist (no Bash, no
// network, no permission bypass). The review writes proposal files under
// ~/.ai/governance/plans/; the human approves and runs: ai amend apply && ai setup --no-hooks
const posixReviewScript = `#!/bin/sh
# AI Governance Review — generated by ai setup
# Tool-restricted: Read/Write/Edit/Glob/Grep only. No shell execution, no bypass.
# Audit review runs every invocation; memory review runs on the 1st of the month.
AI_ROOT="${AI_ROOT:-$HOME/.ai}"
LOG="$AI_ROOT/governance/logs/review.log"
mkdir -p "$(dirname "$LOG")"
echo "--- review $(date -u +%Y-%m-%dT%H:%M:%SZ) ---" >> "$LOG"

claude --allowedTools "Read,Write,Edit,Glob,Grep" \
  -p "$(cat "$AI_ROOT/governance/prompts/audit-review.md")" \
  >> "$LOG" 2>&1

if [ "$(date +%d)" = "01" ]; then
  claude --allowedTools "Read,Write,Edit,Glob,Grep" \
    -p "$(cat "$AI_ROOT/governance/prompts/memory-review.md")" \
    >> "$LOG" 2>&1
fi
`

// windowsReviewScript is the PowerShell equivalent — same tool restriction.
const windowsReviewScript = `# AI Governance Review — generated by ai setup
$AIRoot = if ($env:AI_ROOT) { $env:AI_ROOT } else { "$env:USERPROFILE\.ai" }
$LogDir = "$AIRoot\governance\logs"
New-Item -ItemType Directory -Force -Path $LogDir | Out-Null
$Log = "$LogDir\review.log"
"--- review $(Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ') ---" | Add-Content $Log

claude --allowedTools "Read,Write,Edit,Glob,Grep" ` +
	"`" + `-p (Get-Content "$AIRoot\governance\prompts\audit-review.md" -Raw) ` +
	"`" + `2>&1 | Add-Content $Log

if ((Get-Date -Format "dd") -eq "01") {
    claude --allowedTools "Read,Write,Edit,Glob,Grep" ` +
	"`" + `-p (Get-Content "$AIRoot\governance\prompts\memory-review.md" -Raw) ` +
	"`" + `2>&1 | Add-Content $Log
}
`

// macOSPlist is the launchd agent template. Runs every Sunday at 20:05
// (off the :00 mark to reduce server-side spikes).
const macOSPlist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.ai.governance-review</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/sh</string>
        <string>{{.Script}}</string>
    </array>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Weekday</key><integer>0</integer>
        <key>Hour</key><integer>20</integer>
        <key>Minute</key><integer>5</integer>
    </dict>
    <key>StandardOutPath</key>
    <string>{{.Log}}</string>
    <key>StandardErrorPath</key>
    <string>{{.Log}}</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin</string>
        <key>HOME</key>
        <string>{{.Home}}</string>
    </dict>
</dict>
</plist>
`

// installReviewSchedulers sets up the platform-appropriate scheduled job for
// governance reviews. Q50 cadence values: "default", "weekly-both",
// "monthly-both", "skip".
func installReviewSchedulers(aiRoot, homeDir, cadence string) error {
	if cadence == "" || cadence == "skip" {
		return nil
	}

	if err := writeReviewPrompts(aiRoot); err != nil {
		return err
	}

	switch runtime.GOOS {
	case "darwin":
		return installMacOSReviewSchedule(aiRoot, homeDir)
	case "linux":
		return installLinuxReviewSchedule(aiRoot)
	case "windows":
		return installWindowsReviewSchedule(aiRoot)
	default:
		fmt.Printf("setup: unknown OS %q — skipping scheduler install; run manually:\n", runtime.GOOS)
		fmt.Printf("  %s/governance/review.sh\n", aiRoot)
		return nil
	}
}

// writeReviewPrompts writes the prompt files and the review script to
// ~/.ai/governance/prompts/. Safe to call multiple times (idempotent).
func writeReviewPrompts(aiRoot string) error {
	dir := filepath.Join(aiRoot, "governance", "prompts")
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(aiRoot, "governance", "logs"), 0o750); err != nil {
		return err
	}
	files := map[string]string{
		"audit-review.md":  auditReviewPrompt,
		"memory-review.md": memoryReviewPrompt,
	}
	for name, content := range files {
		p := filepath.Join(dir, name)
		if err := os.WriteFile(p, []byte(content), 0o640); err != nil {
			return err
		}
	}

	// Write platform-appropriate review script.
	if runtime.GOOS == "windows" {
		script := filepath.Join(dir, "review.ps1")
		return os.WriteFile(script, []byte(windowsReviewScript), 0o640)
	}
	script := filepath.Join(dir, "review.sh")
	if err := os.WriteFile(script, []byte(posixReviewScript), 0o750); err != nil { //nolint:gosec
		return err
	}
	return nil
}

func installMacOSReviewSchedule(aiRoot, homeDir string) error {
	agentsDir := filepath.Join(homeDir, "Library", "LaunchAgents")
	if err := os.MkdirAll(agentsDir, 0o750); err != nil {
		return err
	}
	plistPath := filepath.Join(agentsDir, "com.ai.governance-review.plist")
	logPath := filepath.Join(aiRoot, "governance", "logs", "review.log")
	scriptPath := filepath.Join(aiRoot, "governance", "prompts", "review.sh")

	tmpl, err := template.New("plist").Parse(macOSPlist)
	if err != nil {
		return err
	}
	f, err := os.OpenFile(plistPath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o600)
	if err != nil {
		return err
	}
	defer f.Close() //nolint:errcheck
	if err := tmpl.Execute(f, map[string]string{
		"Script": scriptPath,
		"Log":    logPath,
		"Home":   homeDir,
	}); err != nil {
		return err
	}

	// Load the agent (non-fatal: user may not have a GUI session).
	load := exec.Command("launchctl", "load", "-w", plistPath)
	if out, err := load.CombinedOutput(); err != nil {
		fmt.Fprintf(os.Stderr, "setup: warning: launchctl load failed (%v): %s\n", err, out)
		fmt.Fprintf(os.Stderr, "       Run manually: launchctl load -w %s\n", plistPath)
	} else {
		fmt.Printf("setup: review scheduler installed (launchd): %s\n", plistPath)
	}
	return nil
}

func installLinuxReviewSchedule(aiRoot string) error {
	scriptPath := filepath.Join(aiRoot, "governance", "prompts", "review.sh")
	logPath := filepath.Join(aiRoot, "governance", "logs", "review.log")
	entry := fmt.Sprintf("5 20 * * 0 %s >> %s 2>&1  # ai governance review", scriptPath, logPath)

	// Read current crontab, skip if entry already present.
	existing := ""
	out, _ := exec.Command("crontab", "-l").Output()
	existing = string(out)
	if strings.Contains(existing, "ai governance review") {
		fmt.Println("setup: crontab entry already present — skipping.")
		return nil
	}

	updated := strings.TrimRight(existing, "\n") + "\n" + entry + "\n"
	cmd := exec.Command("crontab", "-")
	cmd.Stdin = strings.NewReader(updated)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("setup: crontab install failed: %w\n%s", err, out)
	}
	fmt.Printf("setup: review scheduler installed (crontab): %s\n", entry)
	return nil
}

func installWindowsReviewSchedule(aiRoot string) error {
	scriptPath := filepath.Join(aiRoot, "governance", "prompts", "review.ps1")
	cmd := exec.Command("schtasks", "/Create",
		"/TN", `AI\Governance Review`,
		"/TR", fmt.Sprintf(`powershell -NonInteractive -File "%s"`, scriptPath),
		"/SC", "WEEKLY",
		"/D", "SUN",
		"/ST", "20:05",
		"/F",
	)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("setup: schtasks failed: %w\n%s", err, out)
	}
	fmt.Printf("setup: review scheduler installed (Task Scheduler): AI\\Governance Review\n")
	return nil
}
