// Package compress extracts persona sections from Constitution.md and
// emits YAML derivatives and compact prose fallbacks.
// It is deterministic — no AI calls, no side effects outside the
// returned DerivativeSet.
package compress

import (
	"crypto/sha256"
	"fmt"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/convergent-systems-co/aiConstitution/src/internal/constitution"
)

// DerivativeSet is the output of Extract for one Section.
type DerivativeSet struct {
	YAML    []byte // YAML derivative (for Claude Code + YAML-capable tools)
	Compact []byte // compressed prose derivative (for GitHub Copilot etc.)
	Hash    string // sha256 of source section body (first 16 hex chars)
}

// Extract extracts rules from s and returns the YAML + compact derivatives.
// version is the persona version string (e.g., "0.17") from the source file header.
func Extract(s constitution.Section, version string) (DerivativeSet, error) {
	hash := sourceHash(s.Body)
	rules := extractRules(s)

	yamlBytes, err := marshalYAML(s, version, hash, rules)
	if err != nil {
		return DerivativeSet{}, err
	}

	compact := marshalCompact(s, version, rules)

	return DerivativeSet{
		YAML:    yamlBytes,
		Compact: compact,
		Hash:    hash,
	}, nil
}

// rule is the intermediate representation used for both YAML and compact output.
type rule struct {
	ID             string `yaml:"id"`
	Gate           string `yaml:"gate"`
	NonOverridable bool   `yaml:"non_overridable,omitempty"`
	Label          string `yaml:"label"`
	Content        string `yaml:"content"`
}

// ruleHeadRe matches rule opening lines:
//   **N.M Label.** rest...
//   **PN. Label.** rest...
//   **Label.** rest...
var ruleHeadRe = regexp.MustCompile(`^\s*\*\*(?:(\d+\.\d+)|[A-Z]\d+\.|)([^*]+?)\.*\*\*(.*)$`)

func extractRules(s constitution.Section) []rule {
	var rules []rule
	blocks := strings.Split(s.Body, "\n\n")
	idx := 1
	for _, block := range blocks {
		block = strings.TrimSpace(block)
		if block == "" {
			continue
		}
		r := parseRuleBlock(s.Number, idx, block)
		if r == nil {
			continue
		}
		rules = append(rules, *r)
		idx++
	}
	return rules
}

func parseRuleBlock(sectionNum, ruleIdx int, block string) *rule {
	lines := strings.SplitN(block, "\n", 2)
	firstLine := lines[0]
	rest := ""
	if len(lines) > 1 {
		rest = lines[1]
	}

	m := ruleHeadRe.FindStringSubmatch(firstLine)
	if m == nil {
		return nil
	}

	var id string
	if m[1] != "" {
		id = m[1]
	} else {
		id = fmt.Sprintf("%d.%d", sectionNum, ruleIdx)
	}

	label := strings.TrimSpace(m[2])
	content := strings.TrimSpace(m[3] + " " + rest)
	if label == "" || content == "" {
		return nil
	}

	return &rule{
		ID:             id,
		Gate:           inferGate(content),
		NonOverridable: strings.Contains(content, "(Non-overridable.)") || strings.Contains(content, "*(Non-overridable.)*"),
		Label:          label,
		Content:        content,
	}
}

func inferGate(content string) string {
	upper := strings.ToUpper(content)
	switch {
	case strings.Contains(upper, "MUST NOT") || strings.Contains(upper, "MUST"):
		return "hard"
	case strings.Contains(upper, "SHOULD NOT") || strings.Contains(upper, "SHOULD"):
		return "soft"
	case strings.Contains(upper, "MAY"):
		return "permission"
	default:
		return "soft"
	}
}

func marshalYAML(s constitution.Section, version, hash string, rules []rule) ([]byte, error) {
	header := fmt.Sprintf(
		"# %s — generated by ai compress. Do not edit manually.\n"+
			"# Source: Constitution.md ## %d. %s Rules\n"+
			"# Source hash: sha256:%s\n",
		s.FileName, s.Number, s.Name, hash,
	)

	type yamlDoc struct {
		Persona       string `yaml:"persona"`
		Version       string `yaml:"version"`
		Inherits      string `yaml:"inherits"`
		SourceSection string `yaml:"source_section"`
		SourceHash    string `yaml:"source_hash"`
		Rules         []rule `yaml:"rules"`
	}

	doc := yamlDoc{
		Persona:       s.Slug,
		Version:       version,
		Inherits:      "constitution",
		SourceSection: fmt.Sprintf("%d", s.Number),
		SourceHash:    hash,
		Rules:         rules,
	}

	body, err := yaml.Marshal(doc)
	if err != nil {
		return nil, fmt.Errorf("compress: marshal YAML for %s: %w", s.FileName, err)
	}
	return append([]byte(header), body...), nil
}

func marshalCompact(s constitution.Section, version string, rules []rule) []byte {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("<!-- %s — generated by ai compress. Do not edit manually. -->\n", s.FileName))
	sb.WriteString(fmt.Sprintf("<!-- persona: %s | version: %s | inherits: constitution -->\n\n", s.Slug, version))
	for _, r := range rules {
		gateTag := map[string]string{"hard": "[HARD]", "soft": "[SOFT]", "permission": "[MAY]"}[r.Gate]
		noTag := ""
		if r.NonOverridable {
			noTag = " [NON-OVERRIDABLE]"
		}
		sb.WriteString(fmt.Sprintf("§%s %s%s %s — %s\n\n", r.ID, gateTag, noTag, r.Label, r.Content))
	}
	return []byte(sb.String())
}

func sourceHash(body string) string {
	sum := sha256.Sum256([]byte(body))
	return fmt.Sprintf("%x", sum[:8])
}
